#!/usr/bin/env bash
# Tests for v6.10.0's --discover-streams subcommand and v6.10.1's
# probe-order + --rtsp-port refinements.
#
# Probe priority (v6.10.1):
#   1. /api/go2rtc/streams — Frigate proxy of go2rtc runtime streams.
#      Catches auto-generated streams (e.g. Birdseye when birdseye.restream
#      = true) that don't appear in static /api/config.
#   2. /api/config         — Frigate's main config (static go2rtc.streams).
#   3. /api/streams        — standalone go2rtc.
#
# Discovery is exercised offline via a curl shim that returns fixture
# JSON for known hostnames and exits 22 ("HTTP error") for anything else.

# shellcheck source=lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

cat >"$TMPDIR/curl" <<EOF
#!/usr/bin/env bash
url=\${@: -1}
case "\$url" in
  # Frigate with /api/go2rtc/streams populated (the modern path that
  # surfaces auto-generated Birdseye streams)
  http://test-frigate-proxy/api/go2rtc/streams) cat "$FIXTURES_DIR/frigate-api-go2rtc-streams.json" ;;
  http://test-frigate-proxy/api/config)         cat "$FIXTURES_DIR/frigate-api-config-no-streams.json" ;;
  # Frigate with auto-generated Birdseye only (the issue-#1 reporter shape:
  # /api/config has empty go2rtc.streams but /api/go2rtc/streams has birdseye)
  http://test-frigate-birdseye-only/api/go2rtc/streams) cat "$FIXTURES_DIR/frigate-api-go2rtc-streams-birdseye-only.json" ;;
  http://test-frigate-birdseye-only/api/config)         cat "$FIXTURES_DIR/frigate-api-config-no-streams.json" ;;
  # Frigate hosted via Docker on a non-default external port
  # (web :30059 instead of :5000). RTSP from /api/config says :8554
  # which is the internal listen — should trigger the port-mapping note.
  http://test-frigate-docker:30059/api/go2rtc/streams) cat "$FIXTURES_DIR/frigate-api-go2rtc-streams-birdseye-only.json" ;;
  http://test-frigate-docker:30059/api/config)         cat "$FIXTURES_DIR/frigate-api-config.json" ;;
  # Old Frigate without the /api/go2rtc proxy: only /api/config responds,
  # and it has statically-declared streams.
  http://test-frigate-no-proxy/api/go2rtc/streams) exit 22 ;;
  http://test-frigate-no-proxy/api/config)         cat "$FIXTURES_DIR/frigate-api-config.json" ;;
  # Frigate with RTSP auth (go2rtc.rtsp.username / .password set)
  http://test-frigate-auth/api/go2rtc/streams)     cat "$FIXTURES_DIR/frigate-api-go2rtc-streams-birdseye-only.json" ;;
  http://test-frigate-auth/api/config)             cat "$FIXTURES_DIR/frigate-api-config-with-rtsp-auth.json" ;;
  # Frigate with alternate rtsp.listen port form
  http://test-frigate-rtsp-tcp/api/go2rtc/streams) exit 22 ;;
  http://test-frigate-rtsp-tcp/api/config)         cat "$FIXTURES_DIR/frigate-api-config-rtsp-tcp.json" ;;
  # Frigate with empty everything (both probes return empty streams)
  http://test-frigate-empty/api/go2rtc/streams) printf '{}\n' ;;
  http://test-frigate-empty/api/config)         cat "$FIXTURES_DIR/frigate-api-config-no-streams.json" ;;
  # Standalone go2rtc (no Frigate front door)
  http://test-go2rtc-direct/api/go2rtc/streams) exit 22 ;;
  http://test-go2rtc-direct/api/config)         exit 22 ;;
  http://test-go2rtc-direct/api/streams)        cat "$FIXTURES_DIR/go2rtc-api-streams.json" ;;
  # Completely down host
  http://test-down/api/go2rtc/streams|http://test-down/api/config|http://test-down/api/streams) exit 7 ;;
  # Frigate with birdseye.restream=false (v6.11 advisory path)
  http://test-frigate-bs-false/api/go2rtc/streams) cat "$FIXTURES_DIR/frigate-api-go2rtc-streams.json" ;;
  http://test-frigate-bs-false/api/config)         cat "$FIXTURES_DIR/frigate-api-config-birdseye-restream-false.json" ;;
  *) exit 22 ;;
esac
EOF
chmod +x "$TMPDIR/curl"
export PATH="$TMPDIR:$PATH"

# ---- /api/go2rtc/streams is the preferred path (v6.10.1) -----------------

test_case "frigate-proxy path: detected via /api/go2rtc/streams when populated"
run_kiosk --discover-streams http://test-frigate-proxy
assert_match 'Frigate detected.*via /api/go2rtc/streams' "$LAST_STDOUT"
assert_match 'rtsp://test-frigate-proxy:8554/birdseye' "$LAST_STDOUT"
assert_match 'rtsp://test-frigate-proxy:8554/front_door' "$LAST_STDOUT"
assert_match 'rtsp://test-frigate-proxy:8554/back_yard' "$LAST_STDOUT"

test_case "frigate-proxy path: surfaces auto-generated Birdseye (issue #1 shape)"
# This is the case where /api/config has empty go2rtc.streams but
# birdseye is auto-generated by Frigate's internal ffmpeg and appears
# only on the proxy endpoint. The old v6.10.0 probe order would've
# (incorrectly) reported "no streams configured" here.
run_kiosk --discover-streams http://test-frigate-birdseye-only
assert_match 'rtsp://test-frigate-birdseye-only:8554/birdseye' "$LAST_STDOUT"
assert_eq "0" "$LAST_RC"

# ---- /api/config fallback when /api/go2rtc/streams isn't proxied --------

test_case "frigate fallback: detected via /api/config when go2rtc proxy 404s"
run_kiosk --discover-streams http://test-frigate-no-proxy
assert_match 'Frigate detected.*via /api/config' "$LAST_STDOUT"
assert_match 'rtsp://test-frigate-no-proxy:8554/birdseye' "$LAST_STDOUT"

test_case "frigate fallback: rtsp.listen='tcp://0.0.0.0:9999' parsed correctly"
run_kiosk --discover-streams http://test-frigate-rtsp-tcp
assert_match 'rtsp://test-frigate-rtsp-tcp:9999' "$LAST_STDOUT"

# ---- standalone go2rtc fallback ----------------------------------------

test_case "go2rtc direct: detected when both Frigate endpoints 404"
run_kiosk --discover-streams http://test-go2rtc-direct
assert_match 'go2rtc detected' "$LAST_STDOUT"
assert_match 'rtsp://test-go2rtc-direct:8554/birdseye' "$LAST_STDOUT"

# ---- empty / unreachable / usage paths ---------------------------------

test_case "empty streams: exit 1 + hint about birdseye.restream"
run_kiosk --discover-streams http://test-frigate-empty
assert_eq "1" "$LAST_RC"
assert_match 'no streams configured' "$LAST_STDOUT"
assert_match 'birdseye.restream' "$LAST_STDOUT"

test_case "unreachable host: lists all three probe URLs in error"
run_kiosk --discover-streams http://test-down
assert_eq "1" "$LAST_RC"
assert_match '/api/go2rtc/streams' "$LAST_STDERR"
assert_match '/api/config' "$LAST_STDERR"
assert_match '/api/streams' "$LAST_STDERR"

test_case "no URL argument: usage to stderr, exit 2"
run_kiosk --discover-streams
assert_eq "2" "$LAST_RC"
assert_match 'usage: kiosk-monitor --discover-streams' "$LAST_STDERR"

test_case "trailing slash on URL handled"
run_kiosk --discover-streams http://test-frigate-proxy/
assert_match 'rtsp://test-frigate-proxy:8554/birdseye' "$LAST_STDOUT"

# ---- --rtsp-port override (v6.10.1) ------------------------------------

test_case "--rtsp-port N overrides the discovered port"
run_kiosk --discover-streams http://test-frigate-proxy --rtsp-port 30060
assert_match 'rtsp://test-frigate-proxy:30060/birdseye' "$LAST_STDOUT"
assert_match 'rtsp://test-frigate-proxy:30060/front_door' "$LAST_STDOUT"
assert_match '--rtsp-port override' "$LAST_STDOUT"

test_case "--rtsp-port=N (= form) also supported"
run_kiosk --discover-streams http://test-frigate-proxy --rtsp-port=30060
assert_match 'rtsp://test-frigate-proxy:30060/birdseye' "$LAST_STDOUT"

test_case "--rtsp-port with non-integer rejected"
run_kiosk --discover-streams http://test-frigate-proxy --rtsp-port abc
assert_eq "2" "$LAST_RC"
assert_match '--rtsp-port must be an integer' "$LAST_STDERR"

test_case "--rtsp-port suppresses the Docker port-mapping note"
run_kiosk --discover-streams http://test-frigate-docker:30059 --rtsp-port 30060
assert_no_match 'NOTE.*Docker port-mapping' "$LAST_STDOUT"

test_case "unknown --discover-streams flag rejected"
run_kiosk --discover-streams http://test-frigate-proxy --not-a-flag
assert_eq "2" "$LAST_RC"
assert_match 'unknown --discover-streams option' "$LAST_STDERR"

# ---- Docker port-mapping NOTE ------------------------------------------

test_case "Frigate on non-default web port + internal :8554 triggers Docker note"
run_kiosk --discover-streams http://test-frigate-docker:30059
assert_match 'NOTE.*Docker port-mapping' "$LAST_STDOUT"
assert_match 'docker compose port frigate 8554' "$LAST_STDOUT"
assert_match '--rtsp-port' "$LAST_STDOUT"

test_case "Frigate on the default :5000 does NOT trigger Docker note"
run_kiosk --discover-streams http://test-frigate-proxy
# test-frigate-proxy has no port specified, so parsed.port is None → 5000
assert_no_match 'NOTE.*Docker port-mapping' "$LAST_STDOUT"

# ---- credential extraction (v6.10.2) ------------------------------------

test_case "RTSP credentials in Frigate config are embedded in suggested URLs"
run_kiosk --discover-streams http://test-frigate-auth
# admin / s3cr@t! → admin:s3cr%40t%21 after percent-encoding
assert_match 'rtsp://admin:s3cr%40t%21@test-frigate-auth:8554/birdseye' "$LAST_STDOUT"

test_case "RTSP credentials trigger a NOTE about config sensitivity"
run_kiosk --discover-streams http://test-frigate-auth
assert_match 'NOTE.*RTSP credentials' "$LAST_STDOUT"
assert_match 'go2rtc.rtsp.username' "$LAST_STDOUT"

test_case "no RTSP credentials = no userinfo prefix on URLs"
run_kiosk --discover-streams http://test-frigate-proxy
# Make sure rtsp://userinfo@ pattern is absent
assert_no_match 'rtsp://[^/]+@test-frigate-proxy' "$LAST_STDOUT"

# ---- TUI integration (v6.10.3) ------------------------------------------
# whiptail-based menus are awkward to drive headless. These are
# structural tests: the function exists, the main menu lists the entry,
# both helpers it depends on are in place. Black-box behaviour gets
# verified by ssh demo on the Pi 5 viewport on each release.

test_case "TUI: _tui_discover_streams function exists"
assert_succeeds "function declared" grep -q '^_tui_discover_streams() {$' "$SCRIPT"

test_case "TUI: main menu lists 'discover' entry"
assert_succeeds "menu entry present" grep -q '"discover"   "Discover Frigate / go2rtc RTSP streams"' "$SCRIPT"

test_case "TUI: main-menu case statement dispatches to _tui_discover_streams"
assert_succeeds "case branch present" grep -q 'discover)  _tui_discover_streams' "$SCRIPT"

test_case "TUI: _tui_discover_streams uses discover_frigate_streams"
assert_succeeds "delegation present" bash -c "sed -n '/^_tui_discover_streams() {\$/,/^}\$/p' \"$SCRIPT\" | grep -q discover_frigate_streams"

# ---- birdseye.restream advisory (v6.11 chrome-via-jsmpeg path) ----------

test_case "birdseye NOTE: restream=true triggers both-recipes advisory"
# test-frigate-docker uses frigate-api-config.json which has
# birdseye.enabled=true + birdseye.restream=true.
run_kiosk --discover-streams http://test-frigate-docker:30059
assert_match 'NOTE: birdseye.restream is currently `true`' "$LAST_STDOUT"
assert_match 'CHROME_VIA_JSMPEG' "$LAST_STDOUT"
assert_match 'birdseye.restream: false' "$LAST_STDOUT"
assert_match '/live/jsmpeg/birdseye' "$LAST_STDOUT"

test_case "birdseye NOTE: restream=false steers operator at the freeze-free path"
run_kiosk --discover-streams http://test-frigate-bs-false
assert_match 'NOTE: birdseye.restream is currently `false`' "$LAST_STDOUT"
assert_match 'freeze-free' "$LAST_STDOUT"

test_case "birdseye NOTE: absent when fixture has no birdseye block"
# test-frigate-proxy uses frigate-api-config-no-streams.json which
# has no birdseye key at all → birdseye_enabled stays False → no NOTE.
run_kiosk --discover-streams http://test-frigate-proxy
assert_no_match 'birdseye.restream is currently' "$LAST_STDOUT"

trap _summary EXIT
